## Numpy

Импортировать NumPy под именем np

In [2]:
import numpy as np

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [3]:
[0]*10

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

Создать вектор размера 10, заполненный единицами

In [4]:
[1]*10

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

Создать вектор размера 10, заполненный числом 2.5

In [5]:
[2.5]*10

[2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5]

Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [7]:
arr = [0]*10
arr[4] = 1
print arr

[0, 0, 0, 0, 1, 0, 0, 0, 0, 0]


Развернуть вектор (первый становится последним)

In [15]:
arr = [1,2,3,4,5]
arr.reverse()
print arr

[5, 4, 3, 2, 1]


Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [56]:
i = 0
arr = []
for _ in range(3):
    arr.append(range(i, i+3))
    i+=3
print arr

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]


Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [25]:
result = []
for i, x in enumerate([1,2,0,0,4,0]):
    if x==0:
        result.append(i)
print result

[2, 3, 5]


Создать 3x3 единичную матрицу

In [31]:
numpy.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

Создать массив 3x3x3 со случайными значениями

In [37]:
arr = numpy.random.randint(100, size = (3, 3, 3))
print arr

[[[37 50 75]
  [42 20 51]
  [59 94 75]]

 [[70 79  5]
  [71 54 15]
  [27 79 11]]

 [[18 33 12]
  [72 91 38]
  [53 44 11]]]


Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [38]:
print numpy.random.randint(100, size =(30))

[61  3 14 37 72 80  5 85 88 44 29 31 72 20 66 62  0 77 71  0  3 35 87  8 47
 11 68 41 39  5]


Перемножить матрицы 5x3 и 3x2

In [40]:
arr1 = numpy.random.randint(100, size =(5,3))
arr2 = numpy.random.randint(100, size =(3,2))
print numpy.dot(arr1, arr2)

[[17579  7165]
 [14310  5167]
 [18115  3518]
 [17329  9038]
 [14566  4072]]


Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [45]:
print numpy.random.rand(10)

[ 0.57594443  0.72972784  0.68556876  0.12831378  0.39311727  0.25348345
  0.9256131   0.55840565  0.48416086  0.61300387]


Заменить максимальный элемент на ноль

In [47]:
randArr = numpy.random.rand(10)
randArr[randArr.argmax()]=0
print randArr

[  6.29403025e-04   0.00000000e+00   2.17961687e-01   7.90349192e-01
   1.89571905e-01   5.96017034e-01   7.04855353e-01   3.02475187e-01
   4.62043143e-01   1.25863419e-02]


Преобразовать массив из float в int

In [48]:
randArr = numpy.random.rand(10)*10
print randArr.astype(int)

[1 3 3 1 0 3 8 9 2 6]


Дан массив (10,2) координат, найти расстояние от каждой точки до каждой

In [55]:
coord = numpy.random.randint(100, size =(10,2))
for i in range(len(coord)):
    for k in range(i+1, len(coord)):
        print str(coord[i]) + ", " + str(coord[k]) + " " + str(numpy.linalg.norm(coord[i]-coord[k]))

    

[ 8 50], [93 98] 97.6165969495
[ 8 50], [50 28] 47.4130783645
[ 8 50], [97 11] 97.169954204
[ 8 50], [20 62] 16.9705627485
[ 8 50], [44 39] 37.6430604494
[ 8 50], [27  1] 52.5547333739
[ 8 50], [94 30] 88.2949602186
[ 8 50], [98 51] 90.0055553841
[ 8 50], [67 71] 62.6258732474
[93 98], [50 28] 82.1522975942
[93 98], [97 11] 87.0919054792
[93 98], [20 62] 81.3941029805
[93 98], [44 39] 76.6941979553
[93 98], [27  1] 117.324336776
[93 98], [94 30] 68.0073525437
[93 98], [98 51] 47.2652091924
[93 98], [67 71] 37.483329628
[50 28], [97 11] 49.9799959984
[50 28], [20 62] 45.343136195
[50 28], [44 39] 12.5299640861
[50 28], [27  1] 35.4682957019
[50 28], [94 30] 44.0454310911
[50 28], [98 51] 53.2259335287
[50 28], [67 71] 46.2385120868
[97 11], [20 62] 92.3579991122
[97 11], [44 39] 59.9416382826
[97 11], [27  1] 70.7106781187
[97 11], [94 30] 19.2353840617
[97 11], [98 51] 40.0124980475
[97 11], [67 71] 67.082039325
[20 62], [44 39] 33.2415402772
[20 62], [27  1] 61.400325732
[20 62], [94 

Случайно расположить p элементов в 2D массив

In [67]:
s = 4
twodarr = numpy.zeros((s,s))
p = 3
for _ in range(p):
    rand = numpy.random.randint(s*s)
    twodarr[rand//s][rand%s] = p
print twodarr

[[ 0.  3.  0.  3.]
 [ 0.  0.  0.  0.]
 [ 3.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [78]:
arr = numpy.arange(5)+1
numpy.split(arr, 1)
result = []
for i in arr:
    for k in numpy.dot(i,[1,0,0,0]):
        result.append(k)
print result

[1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5, 0, 0, 0]


Найти наиболее частое значение в массиве

In [79]:
a = np.array([1,2,3,1,2,1,1,1,3,2,2,1])
counts = np.bincount(a)
print np.argmax(counts)

1


Найти n наибольших значений в массиве

In [86]:
a = np.array([1,2,3,1,2,1,1,1,3,2,2,1])
print (a[np.argsort(a)[-3:]])

[2 3 3]


## Pandas - изучение данных

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

Скачать датасет на свой компьютер и распаковать

Считать csv файл в датафрейм food

In [95]:
import pandas as pd
import unicodecsv as csv


codes = []
names = []

food = pd.read_csv('/Users/dmitryzvyagin/projects/bigdata/homework/hw01_data_gathering/en.openfoodfacts.org.products.tsv', delimiter="\t", low_memory=False)

Посмотреть первые 5 записей

In [96]:
print food.head()

            code                                                url  \
0  0000000003087  http://world-en.openfoodfacts.org/product/0000...   
1  0000000004530  http://world-en.openfoodfacts.org/product/0000...   
2  0000000004559  http://world-en.openfoodfacts.org/product/0000...   
3  0000000016087  http://world-en.openfoodfacts.org/product/0000...   
4  0000000016094  http://world-en.openfoodfacts.org/product/0000...   

                      creator   created_t      created_datetime  \
0  openfoodfacts-contributors  1474103866  2016-09-17T09:17:46Z   
1             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
2             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
3             usda-ndb-import  1489055731  2017-03-09T10:35:31Z   
4             usda-ndb-import  1489055653  2017-03-09T10:34:13Z   

  last_modified_t last_modified_datetime                    product_name  \
0      1474103893   2016-09-17T09:18:13Z              Farine de blé noir   
1      1489069957 

Сколько наблюдений в наборе данных?


In [99]:
print food.shape[0]

356027


Сколько столбцов в наборе данных?

In [100]:
print food.shape[1]

163


Напечатайте все названия столбцов

In [101]:
print list(food)

['code', 'url', 'creator', 'created_t', 'created_datetime', 'last_modified_t', 'last_modified_datetime', 'product_name', 'generic_name', 'quantity', 'packaging', 'packaging_tags', 'brands', 'brands_tags', 'categories', 'categories_tags', 'categories_en', 'origins', 'origins_tags', 'manufacturing_places', 'manufacturing_places_tags', 'labels', 'labels_tags', 'labels_en', 'emb_codes', 'emb_codes_tags', 'first_packaging_code_geo', 'cities', 'cities_tags', 'purchase_places', 'stores', 'countries', 'countries_tags', 'countries_en', 'ingredients_text', 'allergens', 'allergens_en', 'traces', 'traces_tags', 'traces_en', 'serving_size', 'no_nutriments', 'additives_n', 'additives', 'additives_tags', 'additives_en', 'ingredients_from_palm_oil_n', 'ingredients_from_palm_oil', 'ingredients_from_palm_oil_tags', 'ingredients_that_may_be_from_palm_oil_n', 'ingredients_that_may_be_from_palm_oil', 'ingredients_that_may_be_from_palm_oil_tags', 'nutrition_grade_uk', 'nutrition_grade_fr', 'pnns_groups_1', 

Какое название у 105 столбца?

In [102]:
print list(food)[104]

-glucose_100g


Какой тип наблюдений в 105 столбце?

In [107]:
print food.dtypes[104]

float64


Как проиндексирован набор данных?

In [108]:
print food.index.values

[     0      1      2 ..., 356024 356025 356026]


Каково значение имени продукта в 19-м наблюдении?

In [109]:
print food.product_name[18]

Lotus Organic Brown Jasmine Rice


## Pandas - фильтрация данных

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

In [110]:
chipo = pd.read_csv('/Users/dmitryzvyagin/projects/bigdata/homework/hw01_data_gathering/chipo.tsv', delimiter="\t", low_memory=False)

Как много продуктов стоят более чем $10.00?

In [130]:

k=0
for i in chipo.item_price:
    price = float(str(i).replace("$","").lstrip())
    if price > 10:
        k+=1
print k

1130


Какова цена каждого предмета? Напечатать столбцы item_name и item_price

In [131]:
print chipo[['item_name', 'item_price']]

                                  item_name item_price
0              Chips and Fresh Tomato Salsa     $2.39 
1                                      Izze     $3.39 
2                          Nantucket Nectar     $3.39 
3     Chips and Tomatillo-Green Chili Salsa     $2.39 
4                              Chicken Bowl    $16.98 
5                              Chicken Bowl    $10.98 
6                             Side of Chips     $1.69 
7                             Steak Burrito    $11.75 
8                          Steak Soft Tacos     $9.25 
9                             Steak Burrito     $9.25 
10                      Chips and Guacamole     $4.45 
11                     Chicken Crispy Tacos     $8.75 
12                       Chicken Soft Tacos     $8.75 
13                             Chicken Bowl    $11.25 
14                      Chips and Guacamole     $4.45 
15    Chips and Tomatillo-Green Chili Salsa     $2.39 
16                          Chicken Burrito     $8.49 
17        

Отсортировать по имени предмета

In [134]:
print chipo.sort_values('item_name')

      order_id  quantity          item_name  \
3389      1360         2  6 Pack Soft Drink   
341        148         1  6 Pack Soft Drink   
1849       749         1  6 Pack Soft Drink   
1860       754         1  6 Pack Soft Drink   
2713      1076         1  6 Pack Soft Drink   
3422      1373         1  6 Pack Soft Drink   
553        230         1  6 Pack Soft Drink   
1916       774         1  6 Pack Soft Drink   
1922       776         1  6 Pack Soft Drink   
1937       784         1  6 Pack Soft Drink   
3836      1537         1  6 Pack Soft Drink   
298        129         1  6 Pack Soft Drink   
1976       798         1  6 Pack Soft Drink   
1167       481         1  6 Pack Soft Drink   
3875      1554         1  6 Pack Soft Drink   
1124       465         1  6 Pack Soft Drink   
3886      1558         1  6 Pack Soft Drink   
2108       849         1  6 Pack Soft Drink   
3010      1196         1  6 Pack Soft Drink   
4535      1803         1  6 Pack Soft Drink   
4169      166

Сколько было заказано самого дорогого предмета?

In [161]:
maxx = chipo.item_price.map(lambda x: float(x.strip().replace("$",""))).max()
print chipo[chipo.item_price.str.contains(str(maxx))]

      order_id  quantity                     item_name choice_description  \
3598      1443        15  Chips and Fresh Tomato Salsa                NaN   

     item_price  
3598    $44.25   


Сколько раз был заказан предмет "Veggie Salad Bowl"?

In [140]:
print chipo[chipo.item_name == "Veggie Salad Bowl"].count()

order_id              18
quantity              18
item_name             18
choice_description    18
item_price            18
dtype: int64


Сколько раз люди заказали более чем 1 предмет "Canned Soda"?

In [142]:
print chipo[(chipo.item_name == "Canned Soda") & (chipo.quantity>1)].count()

order_id              20
quantity              20
item_name             20
choice_description    20
item_price            20
dtype: int64
